# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-202ced80-60dd-4625-a867-4e4bac4dfaec";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-202ced80-60dd-4625-a867-4e4bac4dfaec".device = "/dev/disk/by-uuid/202ced80-60dd-4625-a867-4e4bac4dfaec";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D8B5-3EB5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c7a03bda-692c-44ee-8184-70f9b57a8ee8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
